env:
  browser: true
  es2021: true
extends:
  - next
  - standard
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - unused-imports
  - import
rules:
  sort-imports: 0
  import/no-unresolved: off
  import/named: warn
  import/namespace: warn
  import/no-named-as-default: off
  import/export: warn
  import/order: 
    - error
    - groups:
      - builtin
      - external 
      - parent
      - sibling
      - index
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  no-unused-vars: off
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-vars:
    - warn
    - vars: "all"
      varsIgnorePattern: "^_"
      args: "after-used"
      argsIgnorePattern : "^_"

